djtodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="home"),
    path('detail/<str:pk>', views.detail, name="detail"),
    path('delete/<str:pk>', views.delete, name="delete"),
    path('edit/<str:pk>', views.edit, name="edit")
]

todo/models.py
from django.db import models
import datetime

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)
    posted_date = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=255)
    programmed_date = models.DateField(auto_now=False, auto_now_add=False, default=datetime.datetime.now())

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm, TextInput
from .models import Todo

class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ('title','description','completed', 'programmed_date')
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Enter a todo here'}),
            'description': TextInput(attrs={'placeholder': 'Type the description...'}),
        }

todo/views.py
from django.shortcuts import render, redirect
from .models import Todo
from .forms import TodoForm
# Create your views here.

def index(request):
    todos = Todo.objects.all()
    counting = Todo.objects.count()
    form = TodoForm()
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = TodoForm()
    context = {'todos':todos, 'counting':counting, 'form':form}
    return render(request, "todo/index.html", context)

def detail(request, pk):
    todo = Todo.objects.get(id=pk)
    context = {'todo':todo}
    return render(request, "todo/detail.html", context)

def delete(request, pk):
    todo = Todo.objects.get(id=pk)
    todo.delete()
    return redirect('/')

def edit(request, pk):
    todo = Todo.objects.get(id=pk)
    form = TodoForm(instance=todo)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = TodoForm(instance=todo)
    context = {'form':form}
    return render(request, "todo/edit.html", context)

todo/templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <style type="text/css">
    </style>
    <title>{{todo.title}} - detail</title>
</head>
<body>
    <div class="container bg-indigo-500 text-white max-w-full flex justify-around items-center h-14">
        <p class="text-2xl font-bold">Todo.</p>
    </div>
    
    <div class="container p-10 bg-gray-100 mx-auto my-auto">
        <p class="text-2xl">{{todo.title}}</p>
        <p class="font-extra-light text-gray-500 text-lg">{{todo.description}}</p>
        <p>Created at : {{todo.posted_date}}</p>
        <p class="">Completed : {{todo.completed}}</p>
        <p class="mb-5">Programmed date : {{todo.programmed_date}}</p>

        <a class="bg-green-600 text-white py-2 px-4 font-semibold rounded hover:bg-green-800" href="{% url 'home' %}">Back</a>
    </div>
</body>
</html>

todo/templates/todo/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo - Edit</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <style type="text/css">
        input#id_title{
            border: 1px solid #000;
            width: 250px;
            padding: 2px;
        } 

        input#id_description{
            border: 1px solid #000;
            width: 250px;
            padding: 2px;
            margin-top: 20px;
        } 

        input#id_completed{
            margin-top: 20px;
            margin-bottom: 20px;
        }
        
        input#id_programmed_date{
            margin-bottom: 20px;
            border: 1px solid #000;
            width: 250px;
        }

        a{
            background-color: rgb(218, 42, 42);
            padding: 5px;
            border-radius: 5px;
            color: #fff;
            margin-left: 20px;
        }
    </style>
</head>
<body>
    <div class="container bg-indigo-500 text-white max-w-full flex justify-around items-center h-14">
        <p class="text-2xl font-bold">Todo.</p>
    </div>
    
    <p class="text-3xl mx-10 mt-10">Editing a todo</p>
    <div class="container mx-auto mt-5">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input class="bg-yellow-500 hover:bg-yellow-600 text-white p-1 rounded" type="submit" value="Save changes">
            <a href="{% url 'home' %}">Cancel</a>
        </form>
    </div> 
</body>
</html>

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>ToDo App</title>
</head>
<body>
    <div class="container bg-blue-500 text-white max-w-full flex justify-around items-center h-14">
        <p class="text-2xl font-bold">Todo.</p>
    </div>

    <div class="container bg-gray-200 max-w-3xl rounded-xl mx-auto p-5 mt-8">
        <p class="text-blue-500 text-lg text-center font-semibold mb-5">Todo list ({{counting}})</p>
        <form action="" method="POST" class="flex justify-evenly">
            {% csrf_token %}
            {{form.title}}
            {{form.description}}
            {{form.programmed_date}}
            <br>
            <input class="bg-blue-500 text-white p-1 rounded-xl hover:bg-blue-600" type="submit" value="Add new">
        </form>
        <hr>
        <ul class="mt-10">
            {%for todo in todos%}
                {%if todo.completed%}
                    <strike>
                        <li class="border-b-8 flex justify-between"><a class="hover:text-indigo-500" href="{% url 'detail' todo.id %}">{{todo.title}}</a>
                    </strike>
                {%else%}
                    <li class="border-b-8 flex justify-between"><a class="hover:text-blue-500" href="{% url 'detail' todo.id %}">{{todo.title}}</a>
                {%endif%}
                <div class="action flex justify-between">
                    <a class="hover:text-yellow-400" href="{% url 'edit' todo.id %}">Edit</a>
                    &nbsp;
                    <a class="hover:text-red-500" href="{% url 'delete' todo.id %}">Delete</a>
                </div>    
                </li>
            {%endfor%}
        </ul>
    </div>
    
</body>
</html>